name: Deploy to Databricks Workspace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      DATABRICKS_EMAIL: ${{ secrets.DATABRICKS_EMAIL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Configure Databricks CLI
      run: |
        echo -e "$DATABRICKS_HOST\n$ACCESS_TOKEN\n" | databricks configure --token


    - name: Deploy code to Databricks Workspace
      run: |
        databricks workspace import_dir ./databricks-sql-pipeline /Users/$DATABRICKS_EMAIL/Prod/databricks-sql-pipeline --overwrite
