name: Deploy to Databricks Workspace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_EMAIL: ${{ secrets.DATABRICKS_EMAIL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Configure Databricks CLI
      run: |
        mkdir -p ~/.databricks
        echo "[DEFAULT]" > ~/.databricks/config
        echo "host = $DATABRICKS_HOST" >> ~/.databricks/config
        echo "token = $DATABRICKS_TOKEN" >> ~/.databricks/config

    - name: Deploy code to Databricks Workspace
      run: |
        databricks workspace import_dir ./databricks-sql-pipeline /Users/$DATABRICKS_EMAIL/Prod/databricks-sql-pipeline --overwrite
